# Generated by Django 2.2.6 on 2019-10-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a contest name (e.g. APIO2018, EJOI2009)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a problem name (e.g. Arranging Shoes)', max_length=10)),
                ('oj_id', models.CharField(help_text='Enter a oj.uz problem id (e.g. IOI19_shoes)', max_length=10)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.Contest')),
            ],
        ),
    ]
