# Generated by Django 2.2.6 on 2019-10-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(help_text='Enter a contest name (e.g. APIO2018, EJOI2009)', max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(help_text='Enter a problem name (e.g. Arranging Shoes)', max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='oj_id',
            field=models.CharField(help_text='Enter a oj.uz problem id (e.g. IOI19_shoes)', max_length=100),
        ),
    ]
