# Generated by Django 2.2.6 on 2019-10-12 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20191012_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=18000), help_text='Entar a contest duration'),
        ),
        migrations.AddField(
            model_name='contest',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 30, 17, 646379, tzinfo=utc), help_text='Enter a contest ending time'),
        ),
        migrations.AddField(
            model_name='contest',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 20, 30, 17, 646345, tzinfo=utc), help_text='Enter a contest starting time'),
        ),
    ]
