# Generated by Django 2.2.6 on 2019-10-12 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20191012_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 20, 34, 41, 366607, tzinfo=utc), help_text='Enter a contest ending time'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 20, 34, 41, 366573, tzinfo=utc), help_text='Enter a contest starting time'),
        ),
    ]
