# Generated by Django 2.2.6 on 2019-10-12 20:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20191012_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 35, 47, 167348, tzinfo=utc), help_text='Enter a contest ending time'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='starting_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter a contest starting time'),
        ),
    ]
