# Generated by Django 2.2.6 on 2019-10-12 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20191012_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='secretname',
            field=models.CharField(blank=True, help_text='Enter a contest title (e.g. some japanese tasks)', max_length=100),
        ),
        migrations.AlterField(
            model_name='contest',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 21, 49, 45, 880536, tzinfo=utc), help_text='Enter a contest ending time'),
        ),
    ]
