# Generated by Django 2.2.6 on 2019-10-13 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20191013_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 6, 48, 48, 971255, tzinfo=utc), help_text='Enter a contest ending time'),
        ),
    ]
