# Generated by Django 2.2.6 on 2019-10-13 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20191013_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='finishing_time',
            new_name='ending_time',
        ),
        migrations.AlterField(
            model_name='contest',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 7, 1, 58, 701681, tzinfo=utc), help_text='Enter a contest ending time'),
        ),
    ]
