# Generated by Django 2.2.6 on 2019-10-13 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_auto_20191013_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 7, 45, 24, 715929, tzinfo=utc), help_text='Enter a contest ending time'),
        ),
    ]
